name: qr_scanner
description: "QR Master - Powerful QR code scanner and generator app."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  equatable: ^2.0.8
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.4
  talker_flutter: ^5.1.10
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  clipboard: ^3.0.14
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  apphud: ^3.0.1
  appsflyer_sdk: ^6.17.8
  app_tracking_transparency: ^2.0.6+1
  device_info_plus: ^12.3.0
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/svg/navigation/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf